name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ubuntu-latest:
    runs-on: ubuntu-24.04
    name: Ubuntu 24.04
    steps:
     - name: Checkout
       uses: actions/checkout@v4
     - name: Start build
       run: |
          echo Beginning build
          make
          sudo make install
          make client
  ubuntu-stable:
    runs-on: ubuntu-22.04
    name: Ubuntu 22.04
    steps:
     - name: Checkout
       uses: actions/checkout@v4
     - name: Start build
       run: |
          echo Beginning build
          make
          sudo make install
          make client
  debian-12:
    runs-on: ubuntu-24.04
    name: Debian 12
    container: debian:12
    steps:
      - uses: actions/checkout@v4
      - name: Start build
        run: |
          apt-get -y update
          apt-get -y install make build-essential libssl-dev
          make
          make install
          make client
  debian-11:
    runs-on: ubuntu-24.04
    name: Debian 11
    container: debian:11
    steps:
      - uses: actions/checkout@v4
      - name: Start build
        run: |
          apt-get -y update
          apt-get -y install make build-essential libssl-dev
          make
          make install
          make client
  debian-10:
    runs-on: ubuntu-24.04
    name: Debian 10
    container: debian:10
    steps:
      - uses: actions/checkout@v4
      - name: Start build
        run: |
          apt-get -y update
          apt-get -y install make build-essential libssl-dev
          make
          make install
          make client
  fedora-42:
    runs-on: ubuntu-24.04
    name: Fedora 42
    container: fedora:42
    steps:
      - uses: actions/checkout@v4
      - name: Start build
        run: |
          dnf install -y make gcc openssl-devel
          make
          make install
          make client
  fedora-40:
    runs-on: ubuntu-24.04
    name: Fedora 40
    container: fedora:40
    steps:
      - uses: actions/checkout@v4
      - name: Start build
        run: |
          dnf install -y make gcc openssl-devel
          make
          make install
          make client
  rocky-9:
    runs-on: ubuntu-24.04
    name: Rocky Linux 9.3
    container: rockylinux:9.3
    steps:
      - uses: actions/checkout@v4
      - name: Start build
        run: |
          dnf install -y make gcc openssl-devel
          make
          make install
          make client
  rocky-8:
    runs-on: ubuntu-24.04
    name: Rocky Linux 8.9
    container: rockylinux:8.9
    steps:
      - uses: actions/checkout@v4
      - name: Start build
        run: |
          dnf install -y make gcc openssl-devel
          make
          make install
          make client
  opensuse:
    runs-on: ubuntu-24.04
    name: openSUSE Tumbleweed
    container: opensuse/tumbleweed
    steps:
      - uses: actions/checkout@v4
      - name: Start build
        run: |
          zypper install -y make gcc libopenssl-devel
          make
          make install
          make client
  archlinux:
    runs-on: ubuntu-24.04
    name: Arch Linux
    container: archlinux:latest
    steps:
      - uses: actions/checkout@v4
      - name: Start build
        run: |
          pacman -Sy --noconfirm make gcc
          make
          make install
          make client
  freebsd-14:
    runs-on: ubuntu-24.04
    name: FreeBSD
    steps:
      - uses: actions/checkout@v4
      - name: Start build
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          prepare: |
            pkg install -y gmake lang/gcc
          run: |
            which gcc
            gmake
            gmake install
            gmake client
